### ISSUE TITLE
What does this addon look like in an `@tracked`/Octane world?

### ISSUE THREAD

**Issue by achambers** [adopted-ember-addons/ember-launch-darkly#201]
A placeholder issue to start a discussion around this topic. I'll do some exploration myself and build some context around it here soon. But anyone else interested in diving in is welcome to make a start on it too.

### Brain dump

These functions are going to be related to this:

https://github.com/adopted-ember-addons/ember-launch-darkly/blob/bbe2fe0b96a884fcf6746f39d3fa38b3f8a09ac0/addon/services/launch-darkly.js#L44-L69

This might come in to play too:

https://github.com/adopted-ember-addons/ember-launch-darkly/blob/bbe2fe0b96a884fcf6746f39d3fa38b3f8a09ac0/addon/helpers/variation.js#L25

As is this Babel plugin (potentially, and hopefully, not needed in an `@tracked` world):

https://github.com/adopted-ember-addons/ember-launch-darkly/blob/master/babel-plugin/index.js

**Comment by achambers** [comment]
Ok, I've been spiking this out and I think I have a good idea of where this can get to and I think we can simplify this repo substantially.

Going to knock together a branch with the changes to get a better feel for them and to share some thoughts around the changes.

/cc @mansona

**Comment by achambers** [comment]
@mansona @jaredgalanis @rwwagner90 @patcoll 

I've taken a stab at rewriting this addon in an Octane/`@tracked` world and I'd love to get some feedback and thoughts from any or all of you folks if you have any interest in it.

The PR is #225 however it's not review worthy as yet - I need to clean it up a lot.

But your best bet might be to have a look at the updated [README.md](https://github.com/achambers/ember-launch-darkly/blob/life-in-an-octane-world/README.md) and the new [UPGRADING_TO_1.x.md](https://github.com/achambers/ember-launch-darkly/blob/life-in-an-octane-world/UPGRADING_TO_1.x.md) files that are in the PR. They should give you a good idea as to what the public "api" might look like in the modern Octane world.

The changes are going to hugely simplify things and remove a number of files which is great.

Would need to discuss what this would mean for pre-Octane projects as I'm not sure how we should best handle this so I'm interested in your thoughts on that. But, for now, if you wouldn't mind giving me some feedback on the approach then that'd be much appreciated.

**Comment by achambers** [comment]
Ok, been chatting with @mansona on this and things look positive. Something I'm clearer on now is what the compatibility of this new world looks like.

This is my plan:

1. Release the current https://github.com/adopted-ember-addons/ember-launch-darkly/releases/tag/v1.0.0-beta.0 as `v1.0.0`. This will be the version that is recommended for Ember versions pre 3.12
2. Release the new Octane/tracked friendly version as `v2.0.0` and recommend this for Ember versions 3.12 and above.

This is my plan. If there is any reason to reconsider this, I'd love to hear it @jaredgalanis @rwwagner90 . Otherwise, I'll go ahead and release `v1.0.0` and get the new world changes ready for `v2.0.0`

**Comment by rwwagner90** [comment]
@achambers seems reasonable to me

**Comment by herzzanu** [comment]
@achambers It looks like we've reached this. I'll close for now. Feel free to reopen if needed.
