### ISSUE TITLE
Update launchdarkly-js-client-sdk to newer version

### ISSUE THREAD

**Issue by Ramblurr** [adopted-ember-addons/ember-launch-darkly#316]
We're happily using this addon, but we need some newer features from the underlying LD SDK, namey:

* auto aliasing from [2.19.0](https://github.com/launchdarkly/js-client-sdk/blob/8fc0e3147d13bd148734e96b4d90c2d8e9455722/CHANGELOG.md#2190---2021-01-27)
* `LDOptions.requestHeaderTransform` from [2.20](https://github.com/launchdarkly/js-client-sdk/blob/8fc0e3147d13bd148734e96b4d90c2d8e9455722/CHANGELOG.md#2200---2021-10-15)

Would it be feasible to upgrade? Is it supported to install the SDK in our own `package.json` deps?

**Comment by achambers** [comment]
Hi @Ramblurr . Thanks for the heads up. Let me look in to this and get back to you. It might take me a couple of days. Thanks in advance for your patience.

**Comment by SkoebaSteve** [comment]
just released a new version with the updated SDK: https://github.com/adopted-ember-addons/ember-launch-darkly/releases/tag/v2.1.0
