### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by SkoebaSteve** [adopted-ember-addons/ember-launch-darkly#336]
I would like to release v2.1.0 including which would include the latest SDK version: https://github.com/adopted-ember-addons/ember-launch-darkly/pull/327

I don't believe there are any other urgent dependencies that need to be updated.

**Comment by SkoebaSteve** [comment]
@achambers happy to do this release since I just merged in the updated SDK. Any specific things to keep in mind? I don't think automated release with something like https://github.com/release-it/release-it has been setup(yet)?

Do you normally use the github UI for this? https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes or do this manually locally?

**Comment by achambers** [comment]
@SkoebaSteve release-it is configured: https://github.com/adopted-ember-addons/ember-launch-darkly/blob/085a408829e38edcf050de0f97dd5d38741d490e/package.json#L70

**Comment by achambers** [comment]
I might need to give you permissions to publish the npm package I imagine. Let me look in to it.

**Comment by SkoebaSteve** [comment]
Just released
